language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
install: 
  - pip install --use-mirrors Django==$DJANGO_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors logilab-common==0.57 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install --use-mirrors git+https://github.com/django/django.git  ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install --use-mirrors hg+http://hg.logilab.org/pylint ; fi
  - pip install --use-mirrors -r requirements.txt
script: 
  - python tests/manage.py jenkins --pep8-max-line-length=150 --liveserver=localhost:8090-8100
